### PR TITLE
85769 update with new fam additions

### PR DESCRIPTION
**Pull request by llykkelarsen**
add new properties to tag topic and add punchlistitem pcstopic

### CODE REVIEW

**Comment by paal123** [comment]
Please make sure there are Topics defined in Azure before completing this PR, as we might get a crash in case we dont have this. Might have to also adjsut config in bus sender service to start sending these

**Review by paal123 — APPROVED** [review]
See comment

**Comment by llykkelarsen** [comment]
@paal123 topics are defined in azure (sb-pcd-dev has punchlistitem topic).
pcs-bus-sender-non-prod-config has a topicnames configuration key and this includes punchlistitem. Is that what you meant? Anywhere else I need to check or can I complete the pr?

**Comment by paal123** [comment]
That should be fine

**Pull request merged**
